{% set name = "parsim" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 215859d4ca54250c41ce745cb319f3bd0b5009a6c255ee89942eb1d04010ddba

build:
  noarch: python
  number: 0
  entry_points:
    - psm=parsim.cli:psm_command
    - psm_dakota_driver=parsim.dakota:psm_dakota_driver
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - numpy
    - pandas
    - pydoe3
    - pyexpander >=1.9
    - python >={{ python_min }}
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - parsim
  commands:
    - psm --help

about:
  home: https://gitlab.com/olwi/psm
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: A tool for working with parameterized simulation models
  doc_url: https://parsim.readthedocs.io/en/latest/
  dev_url: https://gitlab.com/olwi/psm

extra:
  recipe-maintainers:
    - olawid
